name: atol_online_dart
description: A sample command-line application.
version: 1.1.1
repository: https://github.com/Taverz/atol_online

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  http: ^1.2.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

dart:
  assets:
    - ../assets/
    - ../assets/mock_request/
    - ../assets/mock_result/
    - ../assets/test_settings/