name: atol_online_dart
description: A Dart package for integrating with ATOL Online service for fiscal data management.
author: Nikita Kovalev nikita3kovalev3@gmail.com
version: 1.1.2
repository: https://github.com/Taverz/atol_online
homepage: https://github.com/Taverz/atol_online
issue_trackerполе: https://github.com/Taverz/atol_online/issue
documentation: https://github.com/Taverz/atol_online/atol_online_dart/DOCS_Official

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  http: ^1.2.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dart:
  assets:
    - ../assets/
    - ../assets/mock_request/
    - ../assets/mock_result/
    - ../assets/test_settings/